import React,{useState} from 'react';
import {useQuery,useQueryClient,useMutation} from '@tanstack/react-query';
import type {PlanningClient} from './generated/lab-client.ts';
import type {ProductionPlan,ProductionTask,ProductionGraphView} from './generated/lab-contracts.ts';
const labels:Record<string,string>={design:'设计',concept:'概念',asset:'资产',animation:'动画',world:'世界',logic:'逻辑',ui:'界面',audio:'音频',vfx:'特效',render:'渲染',build:'构建',test:'测试'};
export const planningLabKeys={plan:(id:string)=>['planning-lab','plan',id] as const,graph:(id:string)=>['planning-lab','graph',id] as const};
function TaskGraph({plan,graph,selected,onSelect}:{plan:ProductionPlan,graph:ProductionGraphView,selected:string,onSelect:(id:string)=>void}){
 const positions=new Map(plan.tasks.map((t,i)=>[t.task_id,{x:30+(i%4)*220,y:30+Math.floor(i/4)*130}]));
 return <svg className="task-graph" viewBox="0 0 910 430" aria-label="生产任务依赖图"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>
 {graph.edges.map(e=>{const a=positions.get(e.source_task_id),b=positions.get(e.target_task_id);if(!a||!b)return null;return <path key={e.dependency_id} className="edge" d={`M${a.x+90},${a.y+68} C${a.x+90},${a.y+112} ${b.x+90},${b.y-40} ${b.x+90},${b.y}`} markerEnd="url(#arrow)"/>})}
 {plan.tasks.map(t=>{const p=positions.get(t.task_id)!;const critical=graph.critical_path.task_ids.includes(t.task_id);return <g key={t.task_id} role="button" tabIndex={0} aria-label={t.title} onClick={()=>onSelect(t.task_id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onSelect(t.task_id)}} transform={`translate(${p.x},${p.y})`} className={selected===t.task_id?'selected':''}><rect width="180" height="68" rx="5"/><text x="12" y="24">{labels[t.workstream]} {critical?'· 关键路径':''}</text><text className="meta" x="12" y="48">{t.status} · {t.estimates[0]?.hours}h 预测</text></g>})}</svg>
}
export function PlanningPanel({client,planId}:{client:PlanningClient,planId:string}){
 const cache=useQueryClient();const [selected,setSelected]=useState('');const [error,setError]=useState('');
 const planQuery=useQuery({queryKey:planningLabKeys.plan(planId),queryFn:()=>client.plan(planId),retry:false});
 const graphQuery=useQuery({queryKey:planningLabKeys.graph(planId),queryFn:()=>client.graph(planId),retry:false});
 const mutation=useMutation({mutationFn:(action:()=>Promise<ProductionPlan>)=>action(),onSuccess:async plan=>{setError('');cache.setQueryData(planningLabKeys.plan(planId),plan);await cache.invalidateQueries({queryKey:planningLabKeys.graph(planId)})},onError:e=>setError(e.message)});
 const run=(action:()=>Promise<ProductionPlan>)=>mutation.mutate(action);
 if(planQuery.isPending||graphQuery.isPending)return <section aria-busy="true">正在读取本地计划…</section>;
 if(planQuery.error||graphQuery.error)return <section role="alert" className="error">本地 API 断开或请求失败：{String(planQuery.error||graphQuery.error)}<button onClick={()=>{planQuery.refetch();graphQuery.refetch()}}>重新连接</button></section>;
 const plan=planQuery.data!,graph=graphQuery.data!,task=plan.tasks.find(t=>t.task_id===selected)||plan.tasks[0];
 return <section><div className="section-title"><div><p className="eyebrow">03 / PRODUCTION PLANNER</p><h2>{plan.feature_title} · 生产计划</h2></div><span className="badge">{plan.execution_mode} · v{plan.plan_version} · {plan.status}</span></div>
 <p className="muted">{plan.tasks.length} 项任务 · {plan.dependencies.length} 条依赖 · 关键路径 {graph.critical_path.total_hours} 小时（predicted 模板估算，非实测）</p>
 <p className="notice">本地领域计算已执行；身份与审批为 mock。资产、Unity、Blender、渲染与测试产物均为 planned，执行 blocked。</p>
 <fieldset disabled={mutation.isPending}><div className="row"><button onClick={()=>run(()=>client.approve(planId,{expected_version:plan.plan_version}))}>确认当前计划 · mock 审批</button><button className="secondary" onClick={()=>{planQuery.refetch();graphQuery.refetch()}}>刷新计划</button></div>
 {error&&<p className="error" role="alert">{error}</p>}
 <TaskGraph plan={plan} graph={graph} selected={task.task_id} onSelect={setSelected}/>
 <div className="plan-columns"><div><h3>任务 / 点击查看和调整</h3><div className="task-list">{plan.tasks.map(t=><button className={t.task_id===task.task_id?'task active':'task'} key={t.task_id} onClick={()=>setSelected(t.task_id)}><span>{labels[t.workstream]} · {t.title}</span><small>{t.status} · {t.assignment.display_name}</small></button>)}</div></div>
 <TaskDetail key={`${task.task_id}:${plan.plan_version}`} task={task} plan={plan} client={client} run={run}/></div>
 <h3>阻断项 · {graph.blockers.length}</h3>{graph.blockers.length===0?<p className="muted">没有结构性阻断；任务完成仍需上游、审批和验收证据。</p>:graph.blockers.map(b=><p className="error" key={b.blocker_id}>{b.code} · {b.message}</p>)}
 <DependencyEditor key={`d:${plan.plan_version}`} plan={plan} client={client} run={run}/>
 <h3>里程碑</h3><div className="milestones">{plan.milestones.map(m=><div key={m.milestone_id}><strong>{m.title}</strong><p>{graph.milestone_readiness.find(r=>r.milestone_id===m.milestone_id)?.state} · {m.required_task_ids.length} 项任务</p><label>名称<input defaultValue={m.title} onBlur={e=>{if(e.target.value!==m.title)run(()=>client.milestones(planId,{expected_version:plan.plan_version,milestones:plan.milestones.map(x=>x.milestone_id===m.milestone_id?{...x,title:e.target.value}:x)}))}}/></label><details><summary>调整必需任务</summary>{plan.tasks.map(t=><label className="checkbox" key={t.task_id}><input type="checkbox" checked={m.required_task_ids.includes(t.task_id)} onChange={e=>run(()=>client.milestones(planId,{expected_version:plan.plan_version,milestones:plan.milestones.map(x=>x.milestone_id===m.milestone_id?{...x,required_task_ids:e.target.checked?[...x.required_task_ids,t.task_id]:x.required_task_ids.filter(id=>id!==t.task_id)}:x)}))}/>{labels[t.workstream]}</label>)}</details></div>)}</div>
 </fieldset></section>
}
function TaskDetail({task,plan,client,run}:{task:ProductionTask,plan:ProductionPlan,client:PlanningClient,run:(fn:()=>Promise<ProductionPlan>)=>void}){
 const [title,setTitle]=useState(task.title),[description,setDescription]=useState(task.description),[owner,setOwner]=useState(task.assignment.display_name),[kind,setKind]=useState(task.assignment.kind),[blocker,setBlocker]=useState(''),[resolution,setResolution]=useState('');
 const base={expected_version:plan.plan_version,task_id:task.task_id};
 return <div className="inspector"><h3>任务详情 · {labels[task.workstream]}</h3><label>标题<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>说明<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="secondary" onClick={()=>run(()=>client.edit(plan.plan_id,{...base,title,description}))}>保存任务</button>
 <label>负责人<input value={owner} onChange={e=>setOwner(e.target.value)}/></label><div className="row"><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="human">人工</option><option value="agent">代理（仅分配，不执行）</option></select><button className="secondary" onClick={()=>run(()=>client.assignment(plan.plan_id,{...base,assignment:{...task.assignment,display_name:owner,assignee_id:owner,kind,confirmed:false}}))}>保存分配</button></div>
 <h4>状态 · {task.status}</h4><div className="row"><button className="secondary" onClick={()=>run(()=>client.transition(plan.plan_id,{...base,target:'ready'}))}>就绪</button><button className="secondary" onClick={()=>run(()=>client.transition(plan.plan_id,{...base,target:'in_progress'}))}>开始</button><button className="secondary" onClick={()=>run(()=>client.transition(plan.plan_id,{...base,target:'completed'}))}>完成（验证证据）</button></div>
 <label>阻断原因<input value={blocker} onChange={e=>setBlocker(e.target.value)}/></label><button className="secondary" disabled={!blocker.trim()} onClick={()=>run(()=>client.transition(plan.plan_id,{...base,target:'blocked',blocker:{blocker_id:crypto.randomUUID(),code:'operational_blocker',message:blocker,task_ids:[task.task_id],resolved:false}}))}>记录 blocker</button>
 {(task.blockers||[]).filter(b=>!b.resolved).map(b=><div key={b.blocker_id}><p className="error">{b.message}</p><label>解决记录引用<input value={resolution} onChange={e=>setResolution(e.target.value)}/></label><button disabled={!resolution.trim()} onClick={()=>run(()=>client.resolve(plan.plan_id,{...base,blocker_id:b.blocker_id,resolution_ref_id:resolution}))}>关联解决记录</button></div>)}
 <details><summary>输入、输出与验收证据</summary><p>输入：{task.inputs.map(x=>x.required_artifact_type).join('、')}</p><p>输出：{task.outputs.map(x=>`${x.artifact_type}（${x.artifact_id||'planned'}）`).join('、')}</p>{task.acceptance.map(a=><p key={a.criterion_id}>{a.criterion_id} → {a.expected_evidence.join('、')}</p>)}<p>已关联证据：{task.evidence?.length||0}；本工作台不伪造产物或测试通过记录。</p></details></div>
}
function DependencyEditor({plan,client,run}:{plan:ProductionPlan,client:PlanningClient,run:(fn:()=>Promise<ProductionPlan>)=>void}){
 const [from,setFrom]=useState(plan.tasks[0].task_id),[to,setTo]=useState(plan.tasks[1].task_id);
 return <details><summary>编辑依赖 · {plan.dependencies.length} 条</summary><p className="muted">删除依赖可能造成任务输入缺少前置条件；循环会保留为可修正的 blocked 草稿，无法确认。</p><div className="row"><select aria-label="前置任务" value={from} onChange={e=>setFrom(e.target.value)}>{plan.tasks.map(t=><option value={t.task_id} key={t.task_id}>{labels[t.workstream]}</option>)}</select><span>→</span><select aria-label="后续任务" value={to} onChange={e=>setTo(e.target.value)}>{plan.tasks.map(t=><option value={t.task_id} key={t.task_id}>{labels[t.workstream]}</option>)}</select><button onClick={()=>run(()=>client.dependencies(plan.plan_id,{expected_version:plan.plan_version,dependencies:[...plan.dependencies,{dependency_id:crypto.randomUUID(),predecessor_task_id:from,successor_task_id:to,required_output_type:plan.tasks.find(t=>t.task_id===from)!.outputs[0].artifact_type}]}))}>添加依赖</button></div>
 {plan.dependencies.map(d=><div className="dependency" key={d.dependency_id}><span>{plan.tasks.find(t=>t.task_id===d.predecessor_task_id)?.title} → {plan.tasks.find(t=>t.task_id===d.successor_task_id)?.title}<small> · {d.required_output_type}</small></span><button className="secondary" onClick={()=>run(()=>client.dependencies(plan.plan_id,{expected_version:plan.plan_version,dependencies:plan.dependencies.filter(x=>x.dependency_id!==d.dependency_id)}))}>移除</button></div>)}</details>
}
