"""Deterministic frontend/backend module catalog generation."""

from __future__ import annotations

import json
import os
import pprint
import re
from pathlib import Path
from typing import Dict, Tuple

from .manifest import (
    BACKEND_ENTRYPOINT_PATTERN,
    FRONTEND_ENTRYPOINT_PATTERN,
    ModuleManifest,
)
from .repository import ModuleGraph


TS_HEADER = "// Generated by scripts/module-generate. Do not edit."
PY_HEADER = "# Generated by scripts/module-generate. Do not edit."
DOC_HEADER = "<!-- Generated by scripts/module-generate. Do not edit. -->"


def _manifest_data(manifest: ModuleManifest):
    return manifest.model_dump(mode="json")


def render_manifest_schema() -> str:
    schema = ModuleManifest.model_json_schema(ref_template="#/$defs/{model}")
    requirements = schema["$defs"]["ModuleRequirements"]["properties"]
    contributions = schema["$defs"]["ModuleContributions"]["properties"]
    for field in ("modules", "integrations", "optional_integrations"):
        requirements[field]["uniqueItems"] = True
    for field in ("editors", "commands", "events", "jobs", "workflows", "policy_gates"):
        contributions[field]["uniqueItems"] = True
    schema["properties"]["permissions"]["uniqueItems"] = True
    entrypoints = schema["$defs"]["ModuleEntrypoints"]
    entrypoints["anyOf"] = [
        {
            "required": ["frontend"],
            "properties": {
                "frontend": {"type": "string", "pattern": FRONTEND_ENTRYPOINT_PATTERN}
            },
        },
        {
            "required": ["backend"],
            "properties": {
                "backend": {"type": "string", "pattern": BACKEND_ENTRYPOINT_PATTERN}
            },
        },
    ]
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = "https://sceneops.local/schemas/module-manifest/v1"
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _typescript_name(module_id: str) -> str:
    words = module_id.split("-")
    return words[0] + "".join(word[:1].upper() + word[1:] for word in words[1:])


def _python_name(module_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", module_id)


def _relative_import(target: Path, origin: Path) -> str:
    relative = Path(os.path.relpath(target, origin)).as_posix()
    return relative if relative.startswith(".") else "./" + relative


def render_frontend_catalog(graph: ModuleGraph, output_path: Path) -> str:
    lines = [TS_HEADER, ""]
    contributions = []
    for source in graph.sources:
        entrypoint = source.manifest.entrypoints.frontend
        if entrypoint is None:
            continue
        variable = _typescript_name(source.manifest.id) + "Contribution"
        import_path = _relative_import((source.directory / entrypoint).resolve(), output_path.parent)
        lines.append(
            f'import {{ moduleContribution as {variable} }} from {json.dumps(import_path)};'
        )
        manifest_path = _relative_import(
            source.directory / "frontend/src/generated/module-manifest.ts", output_path.parent
        )
        lines.append(
            f'import {{ generatedModuleManifest as {variable}Manifest }} from {json.dumps(manifest_path)};'
        )
        contributions.append((source.manifest.id, variable))
    lines.extend(["", "export const generatedFrontendModuleCatalog = ["])
    for module_id, variable in contributions:
        lines.append(f"  {{ ...{variable}, manifest: {variable}Manifest }}, // {module_id}")
    lines.extend(
        [
            "] as const;",
            "",
            "export const generatedFrontendModuleIds = generatedFrontendModuleCatalog.map(",
            "  (contribution) => contribution.manifest.id,",
            ");",
            "",
        ]
    )
    return "\n".join(lines)


def render_backend_catalog(graph: ModuleGraph) -> str:
    lines = [PY_HEADER, ""]
    contributions = []
    for source in graph.sources:
        entrypoint = source.manifest.entrypoints.backend
        if entrypoint is None:
            continue
        variable = _python_name(source.manifest.id) + "_module"
        lines.append(f"import {entrypoint} as {variable}")
        contributions.append((source.manifest, variable))
    lines.extend(["", "GENERATED_BACKEND_MODULE_CATALOG = ("])
    for manifest, variable in contributions:
        value = pprint.pformat(_manifest_data(manifest), sort_dicts=True, width=100)
        lines.append(f'    {{"manifest": {value}, "module": {variable}}},')
    lines.extend(
        [
            ")",
            "",
            "GENERATED_BACKEND_MODULE_IDS = tuple(",
            '    contribution["manifest"]["id"]',
            "    for contribution in GENERATED_BACKEND_MODULE_CATALOG",
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def render_catalog_json(graph: ModuleGraph) -> str:
    payload = {
        "schema_version": 1,
        "generated_by": "scripts/module-generate",
        "registration_order": list(graph.module_ids),
        "modules": [
            {
                **_manifest_data(source.manifest),
                "default_enabled": True,
                "missing_integration_fields": {
                    "required": "requires.integrations",
                    "optional": "requires.optional_integrations",
                },
            }
            for source in graph.sources
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render_module_map(graph: ModuleGraph) -> str:
    lines = [
        DOC_HEADER,
        "# 模块地图",
        "",
        "该文件由已验证的 `module.yaml` 确定性生成。注册顺序遵循模块依赖。",
        "",
        "| 顺序 | 模块 | 版本 | 状态 | 特性开关 | 模块依赖 | 必需集成 | 可选集成 |",
        "|---:|---|---|---|---|---|---|---|",
    ]
    for index, source in enumerate(graph.sources, start=1):
        manifest = source.manifest
        cells = [
            str(index),
            manifest.id,
            manifest.version,
            manifest.status.value,
            manifest.feature_flag,
            ", ".join(manifest.requires.modules) or "—",
            ", ".join(manifest.requires.integrations) or "—",
            ", ".join(manifest.requires.optional_integrations) or "—",
        ]
        lines.append("| " + " | ".join(_escape_cell(cell) for cell in cells) + " |")
    lines.extend(
        [
            "",
            "## 贡献",
            "",
            "| 模块 | Editors | Commands | Events | Jobs |",
            "|---|---|---|---|---|",
        ]
    )
    for source in graph.sources:
        contributions = source.manifest.contributes
        cells = [
            source.manifest.id,
            ", ".join(contributions.editors) or "—",
            ", ".join(contributions.commands) or "—",
            ", ".join(contributions.events) or "—",
            ", ".join(contributions.jobs) or "—",
        ]
        lines.append("| " + " | ".join(_escape_cell(cell) for cell in cells) + " |")
    lines.append("")
    return "\n".join(lines)


def _render_module_typescript_manifest(manifest: ModuleManifest) -> str:
    value = json.dumps(_manifest_data(manifest), indent=2, ensure_ascii=False)
    return f"{TS_HEADER}\n\nexport const generatedModuleManifest = {value} as const;\n"


def _render_module_python_manifest(manifest: ModuleManifest) -> str:
    value = pprint.pformat(_manifest_data(manifest), sort_dicts=True, width=100)
    return f"{PY_HEADER}\n\nGENERATED_MODULE_MANIFEST = {value}\n"


def generated_files(repository_root: Path, graph: ModuleGraph) -> Dict[Path, str]:
    repository_root = repository_root.resolve()
    files: Dict[Path, str] = {
        repository_root / "generated" / "module-catalog.json": render_catalog_json(graph),
        repository_root / "apps" / "web" / "src" / "registries" / "generated-module-catalog.ts": render_frontend_catalog(
            graph,
            repository_root
            / "apps"
            / "web"
            / "src"
            / "registries"
            / "generated-module-catalog.ts",
        ),
        repository_root / "services" / "api" / "generated_module_catalog.py": render_backend_catalog(
            graph
        ),
        repository_root / "docs" / "module-map.md": render_module_map(graph),
        repository_root
        / "modules"
        / "module-runtime"
        / "contracts"
        / "module-manifest.schema.json": render_manifest_schema(),
    }
    for source in graph.sources:
        frontend = source.manifest.entrypoints.frontend
        if frontend is not None:
            files[
                source.directory / "frontend" / "src" / "generated" / "module-manifest.ts"
            ] = _render_module_typescript_manifest(source.manifest)
        backend = source.manifest.entrypoints.backend
        if backend is not None:
            package_path = Path(*backend.split("."))
            files[
                source.directory / "backend" / "src" / package_path / "generated_manifest.py"
            ] = _render_module_python_manifest(source.manifest)
    return files


def write_generated_files(
    repository_root: Path, graph: ModuleGraph, *, check: bool = False
) -> Tuple[Path, ...]:
    changed = []
    for path, content in generated_files(repository_root, graph).items():
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        changed.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return tuple(changed)
