# Generated by scripts/module-generate. Do not edit.

GENERATED_MODULE_MANIFEST = {'contributes': {'commands': ['module.catalog.inspect'],
                 'editors': [],
                 'events': ['module.catalog.generated@1'],
                 'jobs': ['module.catalog.build'],
                 'policy_gates': [],
                 'workflows': []},
 'description': 'Validates static modules and generates deterministic frontend and backend '
                'catalogs.',
 'entrypoints': {'backend': 'module_runtime', 'frontend': './frontend/src/index.ts'},
 'feature_flag': 'module_runtime',
 'id': 'module-runtime',
 'permissions': ['module:read', 'module:generate'],
 'requires': {'integrations': [], 'modules': ['core-kernel'], 'optional_integrations': []},
 'schema_version': 1,
 'status': 'active',
 'title': 'Module Runtime',
 'version': '0.1.0'}
