import {
  defaultAnimatorGraphState,
  defaultCharacterState,
  defaultRetargetState,
  defaultRigState,
  defaultSkinQaState,
  defaultTimelineState,
  restoreAnimatorGraphState,
  restoreCharacterState,
  restoreRetargetState,
  restoreRigState,
  restoreSkinQaState,
  restoreTimelineState,
  serializeEditorState,
} from './editorStates';
import type { EditorDefinition } from './types';

export const characterAnimationEditors: EditorDefinition<any, any>[] = [
  {
    id: 'character.editor',
    title: '角色编辑器',
    icon: 'person',
    category: 'character',
    load: () => import('./editors/CharacterEditor'),
    defaultPlacement: 'center',
    minWidth: 420,
    minHeight: 300,
    singleton: false,
    requiredPermissions: ['character:read'],
    optionalIntegrations: ['unity', 'automatic-rigging'],
    serializeState: serializeEditorState,
    restoreState: (value) => restoreCharacterState(value ?? defaultCharacterState),
  },
  {
    id: 'character.rig-inspector',
    title: 'Rig 检查器',
    icon: 'skeleton',
    category: 'character',
    load: () => import('./editors/RigInspectorEditor'),
    defaultPlacement: 'right',
    minWidth: 360,
    minHeight: 280,
    singleton: false,
    requiredPermissions: ['character:read'],
    optionalIntegrations: ['blender', 'automatic-rigging'],
    serializeState: serializeEditorState,
    restoreState: (value) => restoreRigState(value ?? defaultRigState),
  },
  {
    id: 'character.skin-qa',
    title: '蒙皮质量',
    icon: 'mesh',
    category: 'character',
    load: () => import('./editors/SkinQaEditor'),
    defaultPlacement: 'right',
    minWidth: 340,
    minHeight: 260,
    singleton: false,
    requiredPermissions: ['character:read'],
    optionalIntegrations: ['blender'],
    serializeState: serializeEditorState,
    restoreState: (value) => restoreSkinQaState(value ?? defaultSkinQaState),
  },
  {
    id: 'animation.timeline',
    title: '动画时间线',
    icon: 'timeline',
    category: 'animation',
    load: () => import('./editors/AnimationTimelineEditor'),
    defaultPlacement: 'bottom',
    minWidth: 480,
    minHeight: 240,
    singleton: false,
    requiredPermissions: ['animation:read'],
    optionalIntegrations: ['blender', 'unity'],
    serializeState: serializeEditorState,
    restoreState: (value) => restoreTimelineState(value ?? defaultTimelineState),
  },
  {
    id: 'animation.retarget-preview',
    title: '重定向预览',
    icon: 'retarget',
    category: 'animation',
    load: () => import('./editors/RetargetPreviewEditor'),
    defaultPlacement: 'center',
    minWidth: 480,
    minHeight: 320,
    singleton: false,
    requiredPermissions: ['animation:read'],
    optionalIntegrations: ['retargeting'],
    serializeState: serializeEditorState,
    restoreState: (value) => restoreRetargetState(value ?? defaultRetargetState),
  },
  {
    id: 'animation.animator-graph',
    title: 'Animator 状态图',
    icon: 'graph',
    category: 'animation',
    load: () => import('./editors/AnimatorGraphEditor'),
    defaultPlacement: 'center',
    minWidth: 420,
    minHeight: 300,
    singleton: false,
    requiredPermissions: ['animation:read'],
    optionalIntegrations: ['unity'],
    serializeState: serializeEditorState,
    restoreState: (value) => restoreAnimatorGraphState(value ?? defaultAnimatorGraphState),
  },
];
