# Generated by scripts/module-generate. Do not edit.

GENERATED_MODULE_MANIFEST = {'contributes': {'commands': ['core.run.transition'],
                 'editors': [],
                 'events': ['core.run.state_changed@1'],
                 'jobs': ['core.run.transition'],
                 'policy_gates': ['core.changeset.approval'],
                 'workflows': []},
 'description': 'Enforces shared run-state and ChangeSet safety primitives.',
 'entrypoints': {'backend': 'core_kernel', 'frontend': './frontend/src/index.ts'},
 'feature_flag': 'core_kernel',
 'id': 'core-kernel',
 'permissions': ['core:execute'],
 'requires': {'integrations': [], 'modules': [], 'optional_integrations': []},
 'schema_version': 1,
 'status': 'active',
 'title': 'Core Kernel',
 'version': '0.1.0'}
