from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sceneops_production_planner.models import (
    CreatePlanCommandRequest,
    CreatePlanCommandResponse,
    FeaturePlanningSnapshot,
    PlannerErrorResponse,
    ProductionGraphView,
    ProductionPlan,
    ProductionPlanApprovedPayload,
    ProductionPlanDraftedPayload,
)
from sceneops_production_planner.verification import PlannerExecutionContext
from sceneops_production_planner.fixtures import (
    StaticFeatureSpecProvider,
    UnavailableApprovalProvider,
    UnavailableRunEvidenceProvider,
    key_door_snapshot,
)
from sceneops_production_planner.repository import InMemoryProductionPlanRepository
from sceneops_production_planner.router import create_app
from sceneops_production_planner.service import ProductionPlannerService


MODULE_ROOT = Path(__file__).resolve().parents[2]


def json_text(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "anyOf" in schema:
        return " | ".join(schema_type(option) for option in schema["anyOf"])
    schema_kind = schema.get("type")
    if schema_kind == "array":
        item_type = schema_type(schema.get("items", {}))
        return f"Array<{item_type}>"
    if schema_kind == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {schema_type(additional)}>"
        if additional is True or not schema.get("properties"):
            return "Record<string, unknown>"
        return object_type(schema)
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(schema_kind, "unknown")


def object_type(schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    fields = []
    for name, field_schema in schema.get("properties", {}).items():
        optional = "" if name in required else "?"
        fields.append(f"  {json.dumps(name)}{optional}: {schema_type(field_schema)};")
    return "{\n" + "\n".join(fields) + "\n}"


def collect_types(models: list[type]) -> dict[str, dict[str, Any]]:
    types: dict[str, dict[str, Any]] = {}
    for model in models:
        schema = model.model_json_schema()
        types.update(schema.pop("$defs", {}))
        types[model.__name__] = schema
    return types


def render_typescript(models: list[type]) -> str:
    sections = [
        "// Generated by backend/scripts/export_contracts.py from Pydantic schemas.",
        "// Do not edit by hand.",
        "",
    ]
    for name, schema in sorted(collect_types(models).items()):
        if schema.get("type") == "object" and schema.get("properties"):
            sections.append(f"export interface {name} {object_type(schema)}")
        else:
            sections.append(f"export type {name} = {schema_type(schema)};")
        sections.append("")
    return "\n".join(sections)


def key_door_response() -> CreatePlanCommandResponse:
    snapshot = key_door_snapshot()
    service = ProductionPlannerService(
        InMemoryProductionPlanRepository(),
        StaticFeatureSpecProvider([snapshot]),
        UnavailableRunEvidenceProvider(),
        UnavailableApprovalProvider(),
    )
    request = CreatePlanCommandRequest(
        feature_ref=snapshot.feature_ref,
    )
    context = PlannerExecutionContext(
        actor_id="user:producer",
        ai_initiated=False,
        occurred_at=datetime(2026, 9, 4, 1, 2, 3, tzinfo=timezone.utc),
        execution_mode="mock",
        correlation_id="correlation:key-door-plan",
        command_id="command:create-key-door-plan",
    )
    return service.create_plan(request, context)


def outputs() -> dict[Path, str]:
    frontend_models = [
        CreatePlanCommandRequest,
        CreatePlanCommandResponse,
        PlannerErrorResponse,
        ProductionGraphView,
        ProductionPlan,
    ]
    return {
        MODULE_ROOT / "contracts/openapi.json": json_text(create_app().openapi()),
        MODULE_ROOT / "contracts/manifests/feature-planning-snapshot.schema.json": json_text(FeaturePlanningSnapshot.model_json_schema()),
        MODULE_ROOT / "contracts/manifests/production-plan.schema.json": json_text(ProductionPlan.model_json_schema()),
        MODULE_ROOT / "contracts/manifests/production-graph-view.schema.json": json_text(ProductionGraphView.model_json_schema()),
        MODULE_ROOT / "contracts/events/production-plan.drafted.v1.schema.json": json_text(ProductionPlanDraftedPayload.model_json_schema()),
        MODULE_ROOT / "contracts/events/production-plan.approved.v1.schema.json": json_text(ProductionPlanApprovedPayload.model_json_schema()),
        MODULE_ROOT / "contracts/examples/key-door-production-plan.mock.json": json_text(key_door_response().model_dump(mode="json")),
        MODULE_ROOT / "frontend/src/generated/contracts.ts": render_typescript(frontend_models),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when generated contracts differ.")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(MODULE_ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        print("Generated contracts are stale: " + ", ".join(stale))
        return 1
    print("Generated contracts are current." if args.check else "Generated planner contracts.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
