"""Generate the isolated lab DTOs and transport from Pydantic (no test execution)."""
from pathlib import Path
import json
from sceneops_production_planner import create_planning_lab_app
from export_contracts import render_typescript
from sceneops_design_ai import AiSuggestion, AiRequest, AiResult, ModelCatalog, create_ai_router
from sceneops_production_planner.lab import (LabCreateRequest, LabEditRequest, LabAssignmentRequest,
    LabDependenciesRequest, LabMilestonesRequest, LabApprovalRequest, LabTransitionRequest, LabResolutionRequest)
from sceneops_production_planner.models import CreatePlanCommandResponse, ProductionGraphView, ProductionPlan
root = Path(__file__).resolve().parents[2]
app = create_planning_lab_app()
app.include_router(create_ai_router())
(root / 'contracts/lab-openapi.json').write_text(json.dumps(app.openapi(), ensure_ascii=False, indent=2) + '\n')
ai_target = root.parent / 'design-room/frontend/src/generated'
ai_target.mkdir(exist_ok=True)
(ai_target / 'ai-contracts.ts').write_text(render_typescript([AiSuggestion, AiRequest, AiResult, ModelCatalog]))
models = [LabCreateRequest, LabEditRequest, LabAssignmentRequest, LabDependenciesRequest,
    LabMilestonesRequest, LabApprovalRequest, LabTransitionRequest, LabResolutionRequest,
    CreatePlanCommandResponse, ProductionGraphView, ProductionPlan]
(root / 'frontend/src/generated/lab-contracts.ts').write_text(render_typescript(models))
operations = {'edit':'LabEditRequest','assignment':'LabAssignmentRequest','dependencies':'LabDependenciesRequest',
    'milestones':'LabMilestonesRequest','approve':'LabApprovalRequest','transition':'LabTransitionRequest','resolve':'LabResolutionRequest'}
text = '''// Generated by backend/scripts/export_lab_contracts.py. Do not edit.
import type * as T from './lab-contracts.ts';
import type {AiRequest, AiResult, ModelCatalog} from '../../../../design-room/frontend/src/index.ts';
export function createPlanningClient(base = '', fetchImpl: typeof fetch = fetch) {
  async function request<R>(path: string, body?: unknown): Promise<R> {
    const response = await fetchImpl(base + path, {method: body === undefined ? 'GET' : 'POST',
      headers: {'Content-Type':'application/json'}, body: body === undefined ? undefined : JSON.stringify(body)});
    const value = await response.json();
    if (!response.ok) throw new Error(`${value.code || response.status}: ${value.message || JSON.stringify(value.detail)}${value.details ? ' · ' + JSON.stringify(value.details) : ''}`);
    return value;
  }
  return {
    aiModels: () => request<ModelCatalog>('/v1/design-ai/models'),
    aiSuggest: (body: AiRequest) => request<AiResult>('/v1/design-ai/suggest', body),
    create: (body: T.LabCreateRequest) => request<T.CreatePlanCommandResponse>('/v1/planning-lab/create', body),
    plan: (id: string) => request<T.ProductionPlan>(`/v1/production-planner/plans/${encodeURIComponent(id)}`),
    graph: (id: string) => request<T.ProductionGraphView>(`/v1/production-planner/plans/${encodeURIComponent(id)}/graph`),
'''
for operation, model in operations.items():
    text += f"    {operation}: (id: string, body: T.{model}) => request<T.ProductionPlan>(`/v1/planning-lab/${{encodeURIComponent(id)}}/{operation}`, body),\n"
text += '  };\n}\nexport type PlanningClient = ReturnType<typeof createPlanningClient>;\n'
(root / 'frontend/src/generated/lab-client.ts').write_text(text)
