from __future__ import annotations

from typing import ContextManager, Protocol

from .review_models import (
    ActivityRecord,
    ApprovalObservation,
    AssetLockRecord,
    AssignmentRecord,
    ChangeSetHistoryEntry,
    DecisionRecord,
    ReleaseEvidenceLink,
    ReviewComment,
    ReviewSession,
    RollbackExecution,
    RollbackProposal,
)


class ReviewRepository(Protocol):
    def append_review(
        self,
        review: ReviewSession,
        expected_previous_revision_id: str | None = None,
    ) -> None: ...
    def get_review(self, review_id: str) -> ReviewSession: ...
    def get_review_revision(self, review_revision_id: str) -> ReviewSession: ...
    def guard_review_revision(
        self, review_id: str, review_revision_id: str
    ) -> ContextManager[None]: ...
    def append_comment(self, comment: ReviewComment) -> None: ...
    def list_comments(self, review_id: str) -> tuple[ReviewComment, ...]: ...
    def append_assignment(self, assignment: AssignmentRecord) -> None: ...
    def list_assignments(self, review_id: str) -> tuple[AssignmentRecord, ...]: ...
    def append_decision(self, decision: DecisionRecord) -> None: ...
    def list_decisions(self, review_id: str) -> tuple[DecisionRecord, ...]: ...
    def append_approval(self, approval: ApprovalObservation) -> None: ...
    def list_approvals(self, review_id: str) -> tuple[ApprovalObservation, ...]: ...
    def get_approval(self, approval_id: str) -> ApprovalObservation: ...
    def acquire_lock(self, record: AssetLockRecord) -> None: ...
    def release_lock(self, record: AssetLockRecord) -> None: ...
    def replace_active_lock(self, record: AssetLockRecord) -> None: ...
    def get_active_lock(self, project_id: str, resource_id: str) -> AssetLockRecord | None: ...
    def list_active_locks(self, project_id: str) -> tuple[AssetLockRecord, ...]: ...
    def list_lock_records(self, project_id: str) -> tuple[AssetLockRecord, ...]: ...
    def append_changeset_history(self, entry: ChangeSetHistoryEntry) -> None: ...
    def list_changeset_history(self, change_set_id: str) -> tuple[ChangeSetHistoryEntry, ...]: ...
    def append_activity(self, activity: ActivityRecord) -> None: ...
    def list_activity(self, review_id: str) -> tuple[ActivityRecord, ...]: ...
    def append_rollback_proposal(self, proposal: RollbackProposal) -> None: ...
    def get_rollback_proposal(self, proposal_id: str) -> RollbackProposal: ...
    def append_rollback_execution(self, execution: RollbackExecution) -> None: ...
    def get_rollback_execution(self, proposal_id: str) -> RollbackExecution | None: ...
    def append_release_link(self, link: ReleaseEvidenceLink) -> None: ...
    def list_release_links(self, review_id: str) -> tuple[ReleaseEvidenceLink, ...]: ...
