#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, cast

from fastapi import FastAPI, Request


MODULE_ROOT = Path(__file__).resolve().parents[2]
BACKEND_SRC = MODULE_ROOT / "backend" / "src"
sys.path.insert(0, str(BACKEND_SRC))

from version_collaboration.base import ActionContext  # noqa: E402
from version_collaboration.router import create_router  # noqa: E402
from version_collaboration.service import VersionCollaborationService  # noqa: E402
from version_collaboration.demo import DemoApprovals, DemoCatalog, create_demo_router


def build_openapi() -> dict[str, Any]:
    app = FastAPI(title="SceneOps Version Collaboration API", version="0.1.0")

    def unreachable_context(request: Request) -> ActionContext:
        raise RuntimeError("OpenAPI generation does not execute dependencies")

    app.include_router(
        create_router(cast(VersionCollaborationService, object()), unreachable_context)
    )
    app.include_router(create_demo_router(cast(VersionCollaborationService, object()),
                                          DemoCatalog(entries=()), DemoApprovals()))
    from version_collaboration.tree_router import create_tree_router
    app.include_router(create_tree_router("schema", lambda: Path(".")))
    return app.openapi()


def schema_to_typescript(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(schema_to_typescript(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(schema_to_typescript(item) for item in schema["oneOf"])
    if "allOf" in schema:
        return " & ".join(schema_to_typescript(item) for item in schema["allOf"])
    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        if "prefixItems" in schema:
            members = ", ".join(schema_to_typescript(item) for item in schema["prefixItems"])
            return f"readonly [{members}]"
        return f"ReadonlyArray<{schema_to_typescript(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        members = [
            f"readonly {json.dumps(name)}{'?' if name not in required else ''}: {schema_to_typescript(value)};"
            for name, value in properties.items()
        ]
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            members.append(f"readonly [key: string]: {schema_to_typescript(additional)};")
        elif additional is True:
            members.append("readonly [key: string]: unknown;")
        return "{ " + " ".join(members) + " }"
    return "unknown"


def render_typescript(openapi: dict[str, Any]) -> str:
    lines = [
        "// Generated by backend/scripts/generate_contracts.py. Do not edit.",
        "/* eslint-disable */",
        "",
    ]
    schemas = openapi.get("components", {}).get("schemas", {})
    for name in sorted(schemas):
        lines.append(f"export type {name} = {schema_to_typescript(schemas[name])};")
        lines.append("")
    lines.append("export interface ApiOperations {")
    for path, methods in openapi["paths"].items():
        for method, operation in methods.items():
            if method not in {"get", "post"}:
                continue
            body = operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema")
            result = next(value for code, value in operation["responses"].items() if code.startswith("2"))
            response = result["content"]["application/json"]["schema"]
            params = [p for p in operation.get("parameters", []) if p["in"] == "path"]
            param_type = "{ " + " ".join(f'{p["name"]}: string;' for p in params) + " }"
            lines.append(f'  "{method.upper()} {path}": {{ params: {param_type}; body: {schema_to_typescript(body) if body else "undefined"}; response: {schema_to_typescript(response)} }};')
    lines.append("}")
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text() == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    openapi = build_openapi()
    openapi_text = json.dumps(openapi, indent=2, sort_keys=True) + "\n"
    typescript = render_typescript(openapi)
    results = (
        write_or_check(MODULE_ROOT / "contracts" / "openapi.json", openapi_text, args.check),
        write_or_check(
            MODULE_ROOT / "frontend" / "src" / "generated" / "api-types.ts",
            typescript,
            args.check,
        ),
    )
    if not all(results):
        print("Generated contracts are stale.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
