# Generated by scripts/module-generate. Do not edit.

GENERATED_MODULE_MANIFEST = {'contributes': {'commands': ['runtime.fixture.run'],
                 'editors': ['runtime.fixture'],
                 'events': ['runtime.fixture.completed@1'],
                 'jobs': ['runtime.fixture.execute'],
                 'policy_gates': [],
                 'workflows': []},
 'description': 'Proves deterministic registration, enablement, and explicit success and failure '
                'states.',
 'entrypoints': {'backend': 'runtime_fixture', 'frontend': './frontend/src/index.ts'},
 'feature_flag': 'runtime_fixture',
 'id': 'runtime-fixture',
 'permissions': ['runtime-fixture:read', 'runtime-fixture:execute'],
 'requires': {'integrations': [],
              'modules': ['core-kernel', 'module-runtime'],
              'optional_integrations': ['fixture-renderer']},
 'schema_version': 1,
 'status': 'experimental',
 'title': 'Runtime Fixture',
 'version': '0.1.0'}
