"""Public backend surface for the Asset Library module."""

from .builtin_catalog import BuiltinAssetCatalog, create_builtin_asset_router

from .repository import AssetRepository, InMemoryAssetRepository
from .router import create_router
from .schemas import (
    AIProvenance,
    ArtifactOutput,
    ArtifactProvenance,
    AssetObjectIdentity,
    AssetRecord,
    AssetSearchFilter,
    AssetSpec,
    AssetVersion,
    ExecutionMode,
    GateStatus,
    GeometryMetrics,
    PublicationRequest,
    PublicationStatus,
    QualityGate,
    SourceAsset,
    UnityStatus,
    UsageReference,
    Vector3Meters,
)
from .service import AssetLibraryService, AssetNotFoundError, PublicationBlockedError
from .verification import (
    ArtifactVerifier,
    FinalizedCandidateResolver,
    PublicationApprovalVerifier,
)
from .project_catalog import (
    DoorMaterial,
    DoorRecipe,
    DoorRecipeDefinition,
    ProjectAssetCatalogService,
    ProjectAssetEntry,
    ProjectAssetRegistration,
    ProjectAssetVersion,
    RecipeParameterDescriptor,
    RenameProjectAssetRequest,
    RuntimeArtifactReference,
    SaveProjectAssetResult,
    SqliteProjectAssetRepository,
    UpdateProjectAssetRecipeRequest,
    create_project_catalog_router,
    door_recipe_definition,
    simple_asset_name,
)

__all__ = [
    "BuiltinAssetCatalog", "create_builtin_asset_router",
    "AIProvenance",
    "ArtifactOutput",
    "ArtifactProvenance",
    "DoorMaterial",
    "DoorRecipe",
    "DoorRecipeDefinition",
    "AssetLibraryService",
    "AssetNotFoundError",
    "AssetObjectIdentity",
    "AssetRecord",
    "AssetRepository",
    "AssetSearchFilter",
    "AssetSpec",
    "AssetVersion",
    "ArtifactVerifier",
    "ExecutionMode",
    "FinalizedCandidateResolver",
    "GateStatus",
    "GeometryMetrics",
    "InMemoryAssetRepository",
    "PublicationBlockedError",
    "PublicationApprovalVerifier",
    "PublicationRequest",
    "PublicationStatus",
    "ProjectAssetCatalogService",
    "ProjectAssetEntry",
    "ProjectAssetRegistration",
    "ProjectAssetVersion",
    "QualityGate",
    "RecipeParameterDescriptor",
    "RenameProjectAssetRequest",
    "RuntimeArtifactReference",
    "SaveProjectAssetResult",
    "SqliteProjectAssetRepository",
    "SourceAsset",
    "UnityStatus",
    "UsageReference",
    "UpdateProjectAssetRecipeRequest",
    "Vector3Meters",
    "create_router",
    "create_project_catalog_router",
    "door_recipe_definition",
    "simple_asset_name",
]
from .glb_identity import assign_glb_identities
