import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MarkdownMessage } from '@sceneops/core-ui';
import { SourceIcon } from './SourceIcon';
import { experienceApi, experienceEvidenceLabels, experienceKindLabels, experienceStatusLabels, type ExperienceEntry, type ExperienceTopic } from './experience-client';
export type EntryDraft = {baseRevision:number;title:string;content:string;applicability:string;topics:ExperienceEntry['topics'];memoryCategory:ExperienceEntry['memory_category']};
export const isEntryDraftDirty=(draft:EntryDraft,entry:ExperienceEntry)=>draft.title!==entry.title || draft.content!==entry.content || draft.applicability!==entry.applicability || draft.topics.join(',')!==entry.topics.join(',') || draft.memoryCategory!==entry.memory_category;
const entryDraft=(entry:ExperienceEntry):EntryDraft=>({baseRevision:entry.revision,title:entry.title,content:entry.content,applicability:entry.applicability,topics:entry.topics,memoryCategory:entry.memory_category});
type DetailProps={projectId:string|null;id:string;topics:ExperienceTopic[];draft:EntryDraft|undefined;onDraft:(draft:EntryDraft)=>void;onBack:()=>void};
export function ExperienceDetail({projectId,id,topics,draft,onDraft,onBack}:DetailProps) {
  const entry=useQuery({queryKey:['experience','entry',projectId,id],queryFn:()=>experienceApi.entry(projectId,id),retry:false});
  return <section className="experience-detail" aria-label="经验详情"><div className="experience-detail-top"><button type="button" onClick={onBack}><SourceIcon name="undo"/>返回列表</button><span>经验详情</span></div>{entry.isPending && <p role="status">读取详情…</p>}{entry.error && <p role="alert">读取详情失败：{entry.error.message}<button onClick={()=>void entry.refetch()}>重试</button></p>}{entry.data && <DetailContent projectId={projectId} entry={entry.data} topics={topics} draft={draft ?? entryDraft(entry.data)} onDraft={onDraft}/>}</section>;
}
function DetailContent({projectId,entry,topics,draft,onDraft}:{projectId:string|null;entry:ExperienceEntry;topics:ExperienceTopic[];draft:EntryDraft;onDraft:(draft:EntryDraft)=>void}) {
  const [editing,setEditing]=useState(false); const [historyOpen,setHistoryOpen]=useState(false); const cache=useQueryClient();
  const {title,content,applicability}=draft;
  const dirty=isEntryDraftDirty(draft,entry);
  const reload=useMutation({mutationFn:()=>experienceApi.entry(projectId,entry.id),onSuccess:value=>{onDraft(entryDraft(value));cache.setQueryData(['experience','entry',projectId,entry.id],value);}});
  const revisions=useQuery({queryKey:['experience','revisions',projectId,entry.id],queryFn:()=>experienceApi.revisions(projectId,entry.id),retry:false,enabled:historyOpen});
  const change=useMutation({mutationFn:(action:{kind:'save'|'toggle'|'restore';revision?:number})=>action.kind==='restore'?experienceApi.restore(projectId,entry.id,draft.baseRevision,action.revision!):experienceApi.patch(projectId,entry.id,{expected_revision:draft.baseRevision,...(action.kind==='toggle'?{enabled:!entry.enabled}:{title,content,applicability,topics:draft.topics,memory_category:draft.memoryCategory})}),onSuccess:(value,action)=>{onDraft(action.kind==='toggle'?{...draft,baseRevision:value.revision}:entryDraft(value));cache.setQueryData(['experience','entry',projectId,entry.id],value);if(action.kind==='save')setEditing(false);void cache.invalidateQueries({queryKey:['experience']});}});
  const pending=change.isPending || reload.isPending;
  return <><div className="experience-detail-heading"><div className="experience-chips"><span>{experienceKindLabels[entry.kind]}</span><span data-status={entry.status}>{experienceStatusLabels[entry.status]}</span><span>{entry.scope==='shared'?'共享经验':'项目经验'}</span>{!entry.enabled && <span>已禁用</span>}</div><h3>{entry.title}</h3><div className="experience-detail-meta"><span>v{entry.revision} · {new Date(entry.updated_at).toLocaleDateString('zh-CN')}</span><button type="button" aria-label={editing?'结束编辑':'编辑经验'} disabled={pending} onClick={()=>setEditing(value=>!value)}>{editing?'返回阅读':dirty?'继续编辑':'编辑'}</button></div></div>
    {editing?<form className="experience-editor" onSubmit={event=>{event.preventDefault();change.mutate({kind:'save'});}}><label>标题<input disabled={pending} required maxLength={240} value={title} onChange={event=>onDraft({...draft,title:event.target.value})}/></label><label>适用条件<textarea disabled={pending} rows={2} maxLength={4000} value={applicability} onChange={event=>onDraft({...draft,applicability:event.target.value})}/></label><label>内容<textarea aria-label="经验内容" disabled={pending} required rows={9} maxLength={16000} value={content} onChange={event=>onDraft({...draft,content:event.target.value})}/></label>{entry.scope==='project' && <label>项目记忆分类<select value={draft.memoryCategory ?? 'fact'} onChange={event=>onDraft({...draft,memoryCategory:event.target.value as EntryDraft['memoryCategory']})}><option value="decision">已确认决定</option><option value="constraint">执行约束</option><option value="fact">项目事实</option></select></label>}<fieldset className="experience-topic-picker"><legend>工作场景 <small>最多 3 项</small></legend>{topics.map(topic=><label key={topic.id}><input type="checkbox" checked={draft.topics.includes(topic.id)} disabled={pending || (!draft.topics.includes(topic.id) && draft.topics.length>=3)} onChange={event=>onDraft({...draft,topics:event.target.checked?[...draft.topics,topic.id]:draft.topics.filter(id=>id!==topic.id)})}/>{topic.label}</label>)}</fieldset><small>编辑基于 v{draft.baseRevision}；未保存内容会保留在此窗口。</small><div className="experience-editor-actions"><button className="experience-primary" disabled={pending}>{change.isPending?'保存中…':'保存修改'}</button><button type="button" disabled={pending} onClick={()=>{change.reset();reload.mutate();}}>{dirty?'放弃本次编辑并重新读取':'重新读取'}</button></div></form>:<div className="experience-reading">{dirty && <p className="experience-draft-note">有未保存的编辑，可点击「继续编辑」恢复。</p>}{entry.applicability && <section className="experience-applicability"><span>适用条件</span><p>{entry.applicability}</p></section>}<MarkdownMessage text={entry.content}/><div className="experience-classification"><span className="experience-eyebrow">工作场景 · 工具 / 平台</span><div className="experience-chips">{entry.topics.length?entry.topics.map(id=><span key={id}>{topics.find(topic=>topic.id===id)?.label ?? id}</span>):<span>未分类</span>}{[...entry.domains,...entry.platforms].map((tag,index)=><span key={`${tag}:${index}`}>{tag}</span>)}</div></div></div>}
    {draft.baseRevision!==entry.revision && <p className="experience-draft-note" role="status">服务器已更新到 v{entry.revision}，草稿仍基于 v{draft.baseRevision}。保存时会检查版本。</p>}
    {reload.error && <p role="alert">读取失败，草稿仍保留：{reload.error.message}</p>}{change.error && <p role="alert">操作失败，编辑内容仍保留：{change.error.message}</p>}
    <div className="experience-provenance"><details><summary>来源证据 <span>{entry.evidence.length}</span></summary><p className="experience-muted">来源说明这条经验从何而来，不表示本轮已采用。</p>{entry.evidence.length===0 && <p>暂无来源证据。</p>}{entry.evidence.map(evidence=><article key={evidence.id}><div className="experience-chips"><span>{experienceEvidenceLabels[evidence.verification]}</span><span>{evidence.source_kind}</span></div><p>{evidence.summary}</p><small>{evidence.source_ref}</small></article>)}</details>
    <details onToggle={event=>setHistoryOpen(event.currentTarget.open)}><summary>修订记录与恢复</summary>{revisions.isPending && <p>读取修订记录…</p>}{revisions.error && <p role="alert">读取修订失败：{revisions.error.message}<button onClick={()=>void revisions.refetch()}>重试</button></p>}{revisions.data?.map(revision=><article key={revision.entry.revision}><strong>v{revision.entry.revision} · {revision.entry.title}</strong><p>{revision.entry.content}</p><small>{revision.reason} · {new Date(revision.created_at).toLocaleString('zh-CN')}</small><button disabled={pending || revision.entry.revision===entry.revision} onClick={()=>change.mutate({kind:'restore',revision:revision.entry.revision})}>恢复到此版本</button></article>)}</details></div>
    <footer className="experience-detail-footer"><span>{entry.status==='superseded'?'已被替代，不再提供':entry.enabled?'此经验可作为参考提供':'此经验已停止提供'}</span><button type="button" disabled={pending} onClick={()=>change.mutate({kind:'toggle'})}>{entry.enabled?'禁用经验':'启用经验'}</button></footer>
  </>;
}
