import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { SourceIcon } from './SourceIcon';
import { ExperienceDetail, isEntryDraftDirty, type EntryDraft } from './ExperienceDetail';
import { experienceApi, experienceKindLabels, experienceStatusLabels } from './experience-client';
export function ExperienceLibrary({projectId,open,sharedOnly=false}: {projectId:string|null;open:boolean;sharedOnly?:boolean}) {
  const [search,setSearch]=useState(''); const [topic,setTopic]=useState('all'); const [scope,setScope]=useState(sharedOnly?'shared':'all'); const [kind,setKind]=useState('all'); const [disabled,setDisabled]=useState(false);
  const [evidenceStatus,setEvidenceStatus]=useState('all'); const [tool,setTool]=useState('all');
  const [selected,setSelected]=useState<string|null>(null); const [drafts,setDrafts]=useState<Record<string,EntryDraft>>({});
  const entries=useQuery({queryKey:['experience','entries',projectId,'library'],queryFn:()=>experienceApi.entries(projectId,'','all',true),retry:false,enabled:open});
  const topics=useQuery({queryKey:['experience','topics'],queryFn:experienceApi.topics,retry:false,enabled:open});
  const eligible=(entries.data ?? []).filter(entry=>(disabled || entry.enabled) && (scope==='all' || entry.scope===scope) && (kind==='all' || entry.kind===kind) && (evidenceStatus==='all' || entry.status===evidenceStatus) && (tool==='all' || [...entry.domains,...entry.platforms].includes(tool)) && [entry.title,entry.content,entry.applicability,...entry.domains,...entry.platforms].join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
  const tools=[...new Set((entries.data ?? []).flatMap(entry=>[...entry.domains,...entry.platforms]))].sort();
  const count=(id:string)=>eligible.filter(entry=>id==='all' || (id==='unclassified'?entry.topics.length===0:entry.topics.some(value=>value===id))).length;
  const filtered=eligible.filter(entry=>(topic==='all' || (topic==='unclassified'?entry.topics.length===0:entry.topics.some(value=>value===topic))));
  const selectedTopic=topics.data?.find(item=>item.id===topic);
  return <div className={`experience-library${selected?' has-detail':''}`}>
    <aside className="experience-topics"><span className="experience-eyebrow">按工作场景浏览</span><nav aria-label="经验主题">{[{id:'all',label:'全部经验',description:''},...(topics.data ?? []),{id:'unclassified',label:'未分类',description:''}].map(item=><button key={item.id} type="button" aria-pressed={topic===item.id} title={item.description} onClick={()=>{setTopic(item.id);setSelected(null);}}><span>{item.label}</span><small>{count(item.id)}</small></button>)}</nav><div className="experience-topic-note"><SourceIcon name="shield"/><p>经验是参考上下文。<br/>来源与适用条件始终可查。</p></div>{topics.error && <p role="alert">分类读取失败<button onClick={()=>void topics.refetch()}>重试</button></p>}</aside>
    <main className="experience-browser"><div className="experience-library-heading"><div><h3>{selectedTopic?.label ?? (topic==='unclassified'?'未分类':'全部经验')}</h3><p>{selectedTopic?.description || '浏览可复用的方法、案例与事实。'}</p></div><span>{filtered.length} 条</span></div>
      <label className="experience-search"><SourceIcon name="search"/><input aria-label="搜索经验" placeholder="搜索标题、内容或工具…" value={search} onChange={e=>setSearch(e.target.value)}/>{search && <button type="button" aria-label="清空搜索" onClick={()=>setSearch('')}><SourceIcon name="close"/></button>}</label>
      <div className="experience-filters"><select aria-label="经验范围" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">全部范围</option><option value="project">当前项目方法与案例</option><option value="shared">通用经验</option></select><select aria-label="经验类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">全部类型</option>{Object.entries(experienceKindLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><label><input type="checkbox" checked={disabled} onChange={e=>setDisabled(e.target.checked)}/>含已禁用</label></div>
      <details className="experience-more-filters"><summary>更多筛选{(evidenceStatus!=='all' || tool!=='all') && <span> · 已启用</span>}</summary><div><label>证据状态<select aria-label="证据状态" value={evidenceStatus} onChange={event=>setEvidenceStatus(event.target.value)}><option value="all">全部状态</option>{Object.entries(experienceStatusLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>工具 / 平台<select aria-label="工具 / 平台" value={tool} onChange={event=>setTool(event.target.value)}><option value="all">全部工具与平台</option>{tools.map(value=><option key={value} value={value}>{value}</option>)}</select></label></div></details>
      <div className="experience-entry-list" aria-label="经验列表">{entries.isPending && <p role="status">读取经验…</p>}{entries.error && <p role="alert">读取失败：{entries.error.message}<button onClick={()=>void entries.refetch()}>重试</button></p>}{!entries.isPending && !entries.error && filtered.length===0 && <div className="experience-empty"><SourceIcon name="search"/><h3>这里还没有经验</h3><p>{search?'试试其他关键词，或调整筛选条件。':'新的经验整理完成后，会出现在对应的工作场景中。'}</p></div>}
      {filtered.map(entry=><button type="button" className="experience-entry" key={entry.id} aria-pressed={selected===entry.id} onClick={()=>setSelected(entry.id)}><div className="experience-entry-title"><strong>{entry.title}</strong><SourceIcon name="chevron"/></div><p>{entry.applicability || entry.content}</p><div className="experience-chips"><span>{experienceKindLabels[entry.kind]}</span><span data-status={entry.status}>{experienceStatusLabels[entry.status]}</span><span>{entry.scope==='shared'?'共享':'项目'}</span>{[...entry.domains,...entry.platforms].slice(0,2).map((tag,index)=><span key={`${tag}:${index}`}>{tag}</span>)}{!entry.enabled && <span>已禁用</span>}{drafts[entry.id] && isEntryDraftDirty(drafts[entry.id]!,entry) && <span>有草稿</span>}</div></button>)}</div>
    </main>
    {selected && <ExperienceDetail key={selected} projectId={projectId} id={selected} topics={topics.data ?? []} draft={drafts[selected]} onDraft={draft=>setDrafts(current=>({...current,[selected]:draft}))} onBack={()=>setSelected(null)}/>}
  </div>;
}
