"""Export planning journey contracts without starting tools or generating content."""
import json
from pathlib import Path
from fastapi import FastAPI
from sceneops_design_ai import create_journey_router

app = FastAPI(title='SceneOps Planning Journey')
app.include_router(create_journey_router(None))
target = Path(__file__).resolve().parents[1] / 'modules/design-room/contracts/journey.openapi.json'
target.write_text(json.dumps(app.openapi(), ensure_ascii=False, indent=2) + '\n')

from sceneops_project_workspace import PRODUCTION_DOMAINS
frontend = Path(__file__).resolve().parents[1] / 'modules/project-intake/frontend/src/generated/production-domains.ts'
frontend.parent.mkdir(parents=True, exist_ok=True)
frontend.write_text('// Generated by export-journey-contracts.py; do not edit.\nexport const PRODUCTION_DOMAINS = '+json.dumps(PRODUCTION_DOMAINS, ensure_ascii=False, indent=2)+' as const;\nexport type ProductionDomainId = typeof PRODUCTION_DOMAINS[number]["id"];\n')
