import JSZip from 'jszip';
import type { MaterialState } from './lookdev';
import { graphParameters, parseShaderGraph, shaderNodeReferences, type ShaderGraph, type ShaderNode } from './shader-graph';

const THREE_VERSION = '0.185.1';

function literal(value: string | number) {
  return JSON.stringify(value);
}

export function generateTslMaterialModule(material: MaterialState) {
  if (!material.shaderGraph) throw new Error('当前材质没有可导出的 Shader 图。');
  const graph = parseShaderGraph(material.shaderGraph);
  const nodes = new Map(graph.nodes.map((node) => [node.id, node]));
  const variables = new Map(graph.nodes.map((node, index) => [node.id, `n${index}`]));
  const emitted = new Set<string>();
  const lines: string[] = [];
  const ref = (id: string) => variables.get(id)!;

  function expression(node: ShaderNode): string {
    switch (node.kind) {
      case 'input.uv': return 'uv()';
      case 'input.positionLocal': return 'positionLocal';
      case 'input.normalView': return 'normalView';
      case 'input.viewDirection': return 'positionViewDirection';
      case 'input.time': return 'time';
      case 'input.materialColor': return 'materialColor.rgb';
      case 'input.materialRoughness': return 'materialRoughness';
      case 'input.materialEmissive': return 'materialEmissive';
      case 'input.materialOpacity': return 'materialOpacity';
      case 'value.float': return `float(${literal(node.value)})`;
      case 'value.color': return `color(${literal(node.value)}).rgb`;
      case 'parameter.float': return `float(parameters.${node.key})`;
      case 'parameter.color': return `color(parameters.${node.key}).rgb`;
      case 'vector.component': return `${ref(node.input)}.${node.component}`;
      case 'vector.rotate2d': return `vec2(sub(mul(${ref(node.input)}.x, cos(${ref(node.angle)})), mul(${ref(node.input)}.y, sin(${ref(node.angle)}))), add(mul(${ref(node.input)}.x, sin(${ref(node.angle)})), mul(${ref(node.input)}.y, cos(${ref(node.angle)}))))`;
      case 'math.add': return `add(${ref(node.a)}, ${ref(node.b)})`;
      case 'math.subtract': return `sub(${ref(node.a)}, ${ref(node.b)})`;
      case 'math.multiply': return `mul(${ref(node.a)}, ${ref(node.b)})`;
      case 'math.divide': return `div(${ref(node.a)}, ${ref(node.b)})`;
      case 'math.dot': return `dot(${ref(node.a)}, ${ref(node.b)})`;
      case 'math.mod': return `mod(${ref(node.a)}, ${ref(node.b)})`;
      case 'math.sin': return `sin(${ref(node.input)})`;
      case 'math.abs': return `abs(${ref(node.input)})`;
      case 'math.fract': return `fract(${ref(node.input)})`;
      case 'math.floor': return `floor(${ref(node.input)})`;
      case 'math.oneMinus': return `sub(1, ${ref(node.input)})`;
      case 'math.pow': return `pow(${ref(node.base)}, ${ref(node.exponent)})`;
      case 'math.mix': return `mix(${ref(node.a)}, ${ref(node.b)}, ${ref(node.factor)})`;
      case 'math.smoothstep': return `smoothstep(${ref(node.edge0)}, ${ref(node.edge1)}, ${ref(node.input)})`;
      case 'math.clamp': return `clamp(${ref(node.input)}, ${ref(node.min)}, ${ref(node.max)})`;
      case 'pattern.noise': return `add(mul(mx_noise_float(${ref(node.coordinate)}), 0.5), 0.5)`;
      case 'pattern.stripes': return `add(mul(sin(mul(${ref(node.coordinate)}.x, Math.PI * 2)), 0.5), 0.5)`;
      case 'pattern.checker': return `mod(add(floor(${ref(node.coordinate)}.x), floor(${ref(node.coordinate)}.y)), 2)`;
    }
  }

  function emit(id: string) {
    if (emitted.has(id)) return;
    const node = nodes.get(id);
    if (!node) throw new Error(`Shader 节点不存在：${id}`);
    shaderNodeReferences(node).forEach(emit);
    lines.push(`  const ${ref(id)} = ${expression(node)};`);
    emitted.add(id);
  }
  Object.values(graph.outputs).forEach((id) => { if (id) emit(id); });

  const parameters = graphParameters(graph);
  const parameterType = parameters.map((node) => `  ${node.key}: ${node.kind === 'parameter.float' ? 'number' : 'string'};`).join('\n');
  const parameterDefaults = parameters.map((node) => `  ${node.key}: ${literal(node.value)},`).join('\n');
  const assignments = [
    graph.outputs.color ? `  material.colorNode = ${ref(graph.outputs.color)};` : '',
    graph.outputs.roughness ? `  material.roughnessNode = ${ref(graph.outputs.roughness)};` : '',
    graph.outputs.emissive ? `  material.emissiveNode = ${ref(graph.outputs.emissive)};` : '',
    graph.outputs.opacity ? `  material.opacityNode = ${ref(graph.outputs.opacity)};\n  material.transparent = true;\n  material.depthWrite = false;` : '',
  ].filter(Boolean).join('\n');

  return `// Generated by Lumaform from a validated material graph. No model-generated source is executed by the editor.
import { MeshPhysicalMaterial, MeshPhysicalNodeMaterial } from 'three/webgpu';
import { abs, add, clamp, color, cos, div, dot, float, floor, fract, materialColor, materialEmissive, materialOpacity, materialRoughness, mix, mod, mul, mx_noise_float, normalView, positionLocal, positionViewDirection, pow, sin, smoothstep, sub, time, uv, vec2 } from 'three/tsl';

export type LumaformShaderParameters = {
${parameterType}
};

export const defaultParameters: LumaformShaderParameters = {
${parameterDefaults}
};

export function createLumaformMaterial(parameters: LumaformShaderParameters = defaultParameters, source?: MeshPhysicalMaterial) {
  const material = new MeshPhysicalNodeMaterial();
  if (source) material.copy(source);
  material.name = ${literal(material.name)};
  material.color.set(${literal(material.baseColor)});
  material.metalness = ${material.metalness};
  material.roughness = ${material.roughness};
  material.emissive.set(${literal(material.emissive)});
  material.emissiveIntensity = ${material.emissiveIntensity};
  material.opacity = ${material.opacity};
  material.transmission = ${material.transmission};
  material.ior = ${material.ior};
  material.clearcoat = ${material.clearcoat};
  material.clearcoatRoughness = ${material.clearcoatRoughness};
${lines.join('\n')}
${assignments}
  return material;
}
`;
}

export async function encodeShaderPackage(material: MaterialState) {
  if (!material.shaderGraph) throw new Error('当前材质没有可导出的 Shader 图。');
  const graph: ShaderGraph = parseShaderGraph(material.shaderGraph);
  const zip = new JSZip();
  zip.file('material-graph.json', JSON.stringify(graph, null, 2));
  zip.file('material-state.json', JSON.stringify(material, null, 2));
  zip.file('lumaform-material.ts', generateTslMaterialModule(material));
  zip.file('package.json', JSON.stringify({ private: true, type: 'module', peerDependencies: { three: THREE_VERSION } }, null, 2));
  zip.file('README.md', `# ${graph.name}\n\n${graph.description}\n\n## 使用\n\n此包固定对应 Three.js ${THREE_VERSION}。将 \`lumaform-material.ts\` 放入 Three.js / WebGPU 工程，调用 \`createLumaformMaterial()\`。需要修改参数时，复制 \`defaultParameters\` 并只改变所需字段后传入。\n\n\`material-graph.json\` 是可继续编辑的材质图；\`material-state.json\` 保存基础 PBR 参数。该效果使用模型自身的坐标、法线、视线或 UV，不包含外部纹理。动态效果由 Three.js 的 TSL time 节点驱动。\n`);
  return zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE', compressionOptions: { level: 6 } });
}
