// Generated by scripts/module-generate. Do not edit.

import { moduleContribution as coreKernelContribution } from "../../../../modules/core-kernel/frontend/src/index.ts";
import { generatedModuleManifest as coreKernelContributionManifest } from "../../../../modules/core-kernel/frontend/src/generated/module-manifest.ts";
import { moduleContribution as moduleRuntimeContribution } from "../../../../modules/module-runtime/frontend/src/index.ts";
import { generatedModuleManifest as moduleRuntimeContributionManifest } from "../../../../modules/module-runtime/frontend/src/generated/module-manifest.ts";
import { moduleContribution as aiPlaytestContribution } from "../../../../modules/ai-playtest/frontend/src/index.ts";
import { generatedModuleManifest as aiPlaytestContributionManifest } from "../../../../modules/ai-playtest/frontend/src/generated/module-manifest.ts";
import { moduleContribution as assetLibraryContribution } from "../../../../modules/asset-library/frontend/src/index.ts";
import { generatedModuleManifest as assetLibraryContributionManifest } from "../../../../modules/asset-library/frontend/src/generated/module-manifest.ts";
import { moduleContribution as audioStudioContribution } from "../../../../modules/audio-studio/frontend/src/index.ts";
import { generatedModuleManifest as audioStudioContributionManifest } from "../../../../modules/audio-studio/frontend/src/generated/module-manifest.ts";
import { moduleContribution as engineUnityContribution } from "../../../../modules/engine-unity/frontend/src/index.ts";
import { generatedModuleManifest as engineUnityContributionManifest } from "../../../../modules/engine-unity/frontend/src/generated/module-manifest.ts";
import { moduleContribution as logicStudioContribution } from "../../../../modules/logic-studio/frontend/src/index.ts";
import { generatedModuleManifest as logicStudioContributionManifest } from "../../../../modules/logic-studio/frontend/src/generated/module-manifest.ts";
import { moduleContribution as observabilityContribution } from "../../../../modules/observability/frontend/src/index.ts";
import { generatedModuleManifest as observabilityContributionManifest } from "../../../../modules/observability/frontend/src/generated/module-manifest.ts";
import { moduleContribution as integrationCenterContribution } from "../../../../modules/integration-center/frontend/src/index.ts";
import { generatedModuleManifest as integrationCenterContributionManifest } from "../../../../modules/integration-center/frontend/src/generated/module-manifest.ts";
import { moduleContribution as projectIntakeContribution } from "../../../../modules/project-intake/frontend/src/index.ts";
import { generatedModuleManifest as projectIntakeContributionManifest } from "../../../../modules/project-intake/frontend/src/generated/module-manifest.ts";
import { moduleContribution as designRoomContribution } from "../../../../modules/design-room/frontend/src/index.ts";
import { generatedModuleManifest as designRoomContributionManifest } from "../../../../modules/design-room/frontend/src/generated/module-manifest.ts";
import { moduleContribution as conceptLabContribution } from "../../../../modules/concept-lab/frontend/src/index.ts";
import { generatedModuleManifest as conceptLabContributionManifest } from "../../../../modules/concept-lab/frontend/src/generated/module-manifest.ts";
import { moduleContribution as assetFactoryContribution } from "../../../../modules/asset-factory/frontend/src/index.ts";
import { generatedModuleManifest as assetFactoryContributionManifest } from "../../../../modules/asset-factory/frontend/src/generated/module-manifest.ts";
import { moduleContribution as productionPlannerContribution } from "../../../../modules/production-planner/frontend/src/index.ts";
import { generatedModuleManifest as productionPlannerContributionManifest } from "../../../../modules/production-planner/frontend/src/generated/module-manifest.ts";
import { moduleContribution as characterAnimationContribution } from "../../../../modules/character-animation/frontend/src/index.ts";
import { generatedModuleManifest as characterAnimationContributionManifest } from "../../../../modules/character-animation/frontend/src/generated/module-manifest.ts";
import { moduleContribution as renderOpsContribution } from "../../../../modules/render-ops/frontend/src/index.ts";
import { generatedModuleManifest as renderOpsContributionManifest } from "../../../../modules/render-ops/frontend/src/generated/module-manifest.ts";
import { moduleContribution as runtimeFixtureContribution } from "../../../../modules/runtime-fixture/frontend/src/index.ts";
import { generatedModuleManifest as runtimeFixtureContributionManifest } from "../../../../modules/runtime-fixture/frontend/src/generated/module-manifest.ts";
import { moduleContribution as versionCollaborationContribution } from "../../../../modules/version-collaboration/frontend/src/index.ts";
import { generatedModuleManifest as versionCollaborationContributionManifest } from "../../../../modules/version-collaboration/frontend/src/generated/module-manifest.ts";
import { moduleContribution as buildReleaseContribution } from "../../../../modules/build-release/frontend/src/index.ts";
import { generatedModuleManifest as buildReleaseContributionManifest } from "../../../../modules/build-release/frontend/src/generated/module-manifest.ts";
import { moduleContribution as worldComposerContribution } from "../../../../modules/world-composer/frontend/src/index.ts";
import { generatedModuleManifest as worldComposerContributionManifest } from "../../../../modules/world-composer/frontend/src/generated/module-manifest.ts";
import { moduleContribution as vfxShaderContribution } from "../../../../modules/vfx-shader/frontend/src/index.ts";
import { generatedModuleManifest as vfxShaderContributionManifest } from "../../../../modules/vfx-shader/frontend/src/generated/module-manifest.ts";
import { moduleContribution as aiAgentRuntimeContribution } from "../../../../modules/ai-agent-runtime/frontend/src/index.ts";
import { generatedModuleManifest as aiAgentRuntimeContributionManifest } from "../../../../modules/ai-agent-runtime/frontend/src/generated/module-manifest.ts";
import { moduleContribution as aiPipelineCompilerContribution } from "../../../../modules/ai-pipeline-compiler/frontend/src/index.ts";
import { generatedModuleManifest as aiPipelineCompilerContributionManifest } from "../../../../modules/ai-pipeline-compiler/frontend/src/generated/module-manifest.ts";
import { moduleContribution as conversationHomeContribution } from "../../../../modules/conversation-home/frontend/src/index.ts";
import { generatedModuleManifest as conversationHomeContributionManifest } from "../../../../modules/conversation-home/frontend/src/generated/module-manifest.ts";
import { moduleContribution as forgeShellContribution } from "../../../../modules/forge-shell/frontend/src/index.ts";
import { generatedModuleManifest as forgeShellContributionManifest } from "../../../../modules/forge-shell/frontend/src/generated/module-manifest.ts";
import { moduleContribution as uiStudioContribution } from "../../../../modules/ui-studio/frontend/src/index.ts";
import { generatedModuleManifest as uiStudioContributionManifest } from "../../../../modules/ui-studio/frontend/src/generated/module-manifest.ts";

export const generatedFrontendModuleCatalog = [
  { ...coreKernelContribution, manifest: coreKernelContributionManifest }, // core-kernel
  { ...moduleRuntimeContribution, manifest: moduleRuntimeContributionManifest }, // module-runtime
  { ...aiPlaytestContribution, manifest: aiPlaytestContributionManifest }, // ai-playtest
  { ...assetLibraryContribution, manifest: assetLibraryContributionManifest }, // asset-library
  { ...audioStudioContribution, manifest: audioStudioContributionManifest }, // audio-studio
  { ...engineUnityContribution, manifest: engineUnityContributionManifest }, // engine-unity
  { ...logicStudioContribution, manifest: logicStudioContributionManifest }, // logic-studio
  { ...observabilityContribution, manifest: observabilityContributionManifest }, // observability
  { ...integrationCenterContribution, manifest: integrationCenterContributionManifest }, // integration-center
  { ...projectIntakeContribution, manifest: projectIntakeContributionManifest }, // project-intake
  { ...designRoomContribution, manifest: designRoomContributionManifest }, // design-room
  { ...conceptLabContribution, manifest: conceptLabContributionManifest }, // concept-lab
  { ...assetFactoryContribution, manifest: assetFactoryContributionManifest }, // asset-factory
  { ...productionPlannerContribution, manifest: productionPlannerContributionManifest }, // production-planner
  { ...characterAnimationContribution, manifest: characterAnimationContributionManifest }, // character-animation
  { ...renderOpsContribution, manifest: renderOpsContributionManifest }, // render-ops
  { ...runtimeFixtureContribution, manifest: runtimeFixtureContributionManifest }, // runtime-fixture
  { ...versionCollaborationContribution, manifest: versionCollaborationContributionManifest }, // version-collaboration
  { ...buildReleaseContribution, manifest: buildReleaseContributionManifest }, // build-release
  { ...worldComposerContribution, manifest: worldComposerContributionManifest }, // world-composer
  { ...vfxShaderContribution, manifest: vfxShaderContributionManifest }, // vfx-shader
  { ...aiAgentRuntimeContribution, manifest: aiAgentRuntimeContributionManifest }, // ai-agent-runtime
  { ...aiPipelineCompilerContribution, manifest: aiPipelineCompilerContributionManifest }, // ai-pipeline-compiler
  { ...conversationHomeContribution, manifest: conversationHomeContributionManifest }, // conversation-home
  { ...forgeShellContribution, manifest: forgeShellContributionManifest }, // forge-shell
  { ...uiStudioContribution, manifest: uiStudioContributionManifest }, // ui-studio
] as const;

export const generatedFrontendModuleIds = generatedFrontendModuleCatalog.map(
  (contribution) => contribution.manifest.id,
);
