/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects/{project_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_projects__project_id__exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_api_projects__project_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_api_projects__project_id__exports__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/platforms/{platform}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue Export */
        post: operations["continue_export_api_projects__project_id__exports__task_id__platforms__platform__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/platforms/{platform}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Export */
        post: operations["cancel_export_api_projects__project_id__exports__task_id__platforms__platform__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/platforms/{platform}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Export */
        post: operations["verify_export_api_projects__project_id__exports__task_id__platforms__platform__verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Consent */
        post: operations["export_consent_api_projects__project_id__exports__task_id__settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message Export */
        post: operations["message_export_api_projects__project_id__exports__task_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/agent/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Export Agent */
        post: operations["cancel_export_agent_api_projects__project_id__exports__task_id__agent_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/refresh-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Export Source */
        post: operations["refresh_export_source_api_projects__project_id__exports__task_id__refresh_source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_projects__project_id__exports__task_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/exports/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Events */
        get: operations["export_events_api_projects__project_id__exports__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateExportRequest */
        CreateExportRequest: {
            /**
             * Execution Mode
             * @default fixed
             * @enum {string}
             */
            execution_mode: "native" | "fixed";
            /**
             * Accept Full Access
             * @default false
             */
            accept_full_access: boolean;
            /** Platforms */
            platforms: ("android" | "mac-arm64" | "mac-x64" | "win-x64")[];
            settings?: components["schemas"]["ExportSettings"];
        };
        /** ExportArtifact */
        ExportArtifact: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Download Url */
            download_url: string;
        };
        /** ExportAttempt */
        ExportAttempt: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted" | "blocked";
            settings?: components["schemas"]["ExportSettings"];
            /**
             * Stage
             * @default queued
             */
            stage: string;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Logs */
            logs?: components["schemas"]["ExportLog"][];
            /** Error */
            error?: string | null;
            /** Artifacts */
            artifacts?: components["schemas"]["ExportArtifact"][];
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** ExportConsentRequest */
        ExportConsentRequest: {
            /** Allow Dependency Install */
            allow_dependency_install: boolean;
        };
        /** ExportLog */
        ExportLog: {
            /** Timestamp */
            timestamp: string;
            /** Stage */
            stage: string;
            /** Message */
            message: string;
        };
        /** ExportMessage */
        ExportMessage: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Agent Task Id */
            agent_task_id?: string | null;
            /** Provider Id */
            provider_id?: string | null;
            /** Model */
            model?: string | null;
            /** Usage */
            usage?: {
                [key: string]: unknown;
            };
            /** Proposed Development */
            proposed_development?: string | null;
            /** Invocation */
            invocation?: {
                [key: string]: unknown;
            };
        };
        /** ExportMessageRequest */
        ExportMessageRequest: {
            /** Content */
            content: string;
            /**
             * Execution Mode
             * @default discuss
             * @enum {string}
             */
            execution_mode: "native" | "discuss";
            /**
             * Accept Full Access
             * @default false
             */
            accept_full_access: boolean;
            /** Provider Id */
            provider_id?: string | null;
            /** Model */
            model?: string | null;
        };
        /** ExportNativeRun */
        ExportNativeRun: {
            /** Id */
            id: string;
            /** Agent Task Id */
            agent_task_id?: string | null;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "pending" | "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted" | "blocked";
            /** Logs */
            logs?: components["schemas"]["ExportLog"][];
            /** Error */
            error?: string | null;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** ExportPlatformRun */
        ExportPlatformRun: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "android" | "mac-arm64" | "mac-x64" | "win-x64";
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "pending" | "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted" | "blocked";
            /** Attempts */
            attempts?: components["schemas"]["ExportAttempt"][];
            /**
             * Verification
             * @default pending
             * @enum {string}
             */
            verification: "pending" | "passed" | "failed";
            /**
             * Verification Notes
             * @default
             */
            verification_notes: string;
            /**
             * Verification Device
             * @default
             */
            verification_device: string;
            /** Verification Attempt Id */
            verification_attempt_id?: string | null;
        };
        /** ExportSettings */
        ExportSettings: {
            /**
             * App Name
             * @default
             */
            app_name: string;
            /**
             * App Id
             * @default
             */
            app_id: string;
            /**
             * Orientation
             * @default landscape
             * @enum {string}
             */
            orientation: "landscape" | "portrait";
            /**
             * Allow Dependency Install
             * @default false
             */
            allow_dependency_install: boolean;
        };
        /** ExportTask */
        ExportTask: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Source Version */
            source_version: string;
            /** Previous Task Id */
            previous_task_id?: string | null;
            settings: components["schemas"]["ExportSettings"];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Mode
             * @default live
             * @enum {string}
             */
            mode: "live" | "mock" | "blocked" | "planned";
            /** Platforms */
            platforms: components["schemas"]["ExportPlatformRun"][];
            /** Messages */
            messages?: components["schemas"]["ExportMessage"][];
            /** Native Runs */
            native_runs?: components["schemas"]["ExportNativeRun"][];
            /**
             * Revision
             * @default 0
             */
            revision: number;
        };
        /** ExportVerificationRequest */
        ExportVerificationRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "passed" | "failed";
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Device
             * @default
             */
            device: string;
            /** Attempt Id */
            attempt_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_exports_api_projects__project_id__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_projects__project_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_api_projects__project_id__exports__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_export_api_projects__project_id__exports__task_id__platforms__platform__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
                platform: "android" | "mac-arm64" | "mac-x64" | "win-x64";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_export_api_projects__project_id__exports__task_id__platforms__platform__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
                platform: "android" | "mac-arm64" | "mac-x64" | "win-x64";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_export_api_projects__project_id__exports__task_id__platforms__platform__verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
                platform: "android" | "mac-arm64" | "mac-x64" | "win-x64";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_consent_api_projects__project_id__exports__task_id__settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_export_api_projects__project_id__exports__task_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_export_agent_api_projects__project_id__exports__task_id__agent_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_export_source_api_projects__project_id__exports__task_id__refresh_source_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_projects__project_id__exports__task_id__artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_events_api_projects__project_id__exports__task_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
