"""Generated TypeScript test protocol shared by both real game templates."""


def test_adapter_files() -> dict[str, str]:
    return {"src/game/sceneops-test.ts": """// Generated by SceneOps: test controls observe the original gameplay loop.
export type Position = { x: number; y: number; z: number }
export type GameplayDiagnostics = {
  player: Position
  score: number
  collectibles: (Position & { id: string; collected: boolean; visible: boolean })[]
}
export type Diagnostics = GameplayDiagnostics & {
  state_id: 'start'
  simulation: { paused: boolean; steps: number; elapsed_seconds: number }
  randomness: { kind: 'none'; description: 'fixed positions; no random source' }
}
export type SceneOpsTest = {
  version: 1
  states(): { id: 'start'; description: string }[]
  setState(id: string): Diagnostics
  pause(): void
  resume(): void
  diagnostics(): Diagnostics
}
declare global { interface Window { __sceneopsTest?: SceneOpsTest } }

export function createTestAdapter(reset: () => void, read: () => GameplayDiagnostics) {
  let paused = false, steps = 0, elapsed = 0
  const diagnostics = (): Diagnostics => ({
    ...read(), state_id: 'start', simulation: { paused, steps, elapsed_seconds: elapsed },
    randomness: { kind: 'none', description: 'fixed positions; no random source' },
  })
  const protocol: SceneOpsTest = {
    version: 1,
    states: () => [{ id: 'start', description: 'Original spawn, zero score, all collectibles available' }],
    setState(id) {
      if (id !== 'start') throw new Error(`Unknown SceneOps test state: ${id}`)
      reset(); paused = false; steps = 0; elapsed = 0
      return diagnostics()
    },
    pause() { paused = true },
    resume() { paused = false },
    diagnostics,
  }
  return {
    protocol,
    get paused() { return paused },
    recordFrame(delta: number) { steps += 1; elapsed += delta },
  }
}
"""}
