"""Generate JSON Schemas, OpenAPI, examples, and event schemas from Pydantic."""

import json
from pathlib import Path
from typing import Dict

from fastapi import FastAPI

from sceneops_character_animation.adapter import DeterministicMockCharacterToolAdapter
from sceneops_character_animation.event_models import EVENT_MODELS
from sceneops_character_animation.fixtures import fixed_preview_camera, remember_home_bundle
from sceneops_character_animation.operation_models import (
    CharacterAnimationContractCatalog,
    PreviewCaptureRequest,
    UnityMappingProposalRequest,
)
from sceneops_character_animation.router import router
from sceneops_character_animation.service import CharacterAnimationService


BACKEND_ROOT = Path(__file__).resolve().parents[1]
MODULE_ROOT = BACKEND_ROOT.parent


def write_json(path: Path, value: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def export_openapi() -> None:
    app = FastAPI(title="SceneOps Character and Animation API", version="0.1.0")
    app.include_router(router)
    schema = app.openapi()
    schema["info"]["x-generated-by"] = "backend/scripts/export_contracts.py"
    write_json(BACKEND_ROOT / "openapi.json", schema)


def export_catalog_schema() -> None:
    schema = CharacterAnimationContractCatalog.model_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = "https://sceneops.example/contracts/character-animation/v1"
    schema["$comment"] = "Generated by backend/scripts/export_contracts.py; do not edit."
    write_json(MODULE_ROOT / "contracts/manifests/character-animation.schema.json", schema)


def export_event_schemas() -> None:
    for event_type, model in EVENT_MODELS.items():
        schema = model.model_json_schema()
        schema["x-event-type"] = event_type
        schema["x-event-version"] = 1
        schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        schema["$id"] = "https://sceneops.example/events/{}/v1".format(event_type)
        schema["$comment"] = "Generated by backend/scripts/export_contracts.py; do not edit."
        filename = "{}.v1.schema.json".format(event_type)
        write_json(MODULE_ROOT / "contracts/events" / filename, schema)


def export_fixture() -> None:
    bundle = remember_home_bundle()
    write_json(MODULE_ROOT / "contracts/examples/remember-home-character.json", bundle.model_dump(mode="json"))
    service = CharacterAnimationService(adapter=DeterministicMockCharacterToolAdapter())
    preview = service.capture_preview(
        PreviewCaptureRequest(
            request_id="remember_home_idle",
            character=bundle.character,
            rig=bundle.rig,
            clip=bundle.clips[0],
            camera=fixed_preview_camera(),
        )
    )
    write_json(MODULE_ROOT / "contracts/examples/preview-artifact.json", preview.model_dump(mode="json"))
    proposal = service.propose_unity_mapping(
        UnityMappingProposalRequest(
            request_id="remember_home_unity",
            bundle=bundle,
            unity_prefab_id="prefab_homekeeper_v1",
            unity_game_object_sceneops_id="sceneobj_player_homekeeper",
            unity_animator_controller_id="animator_homekeeper_v1",
            base_unity_version="unity_project_12",
        )
    )
    write_json(MODULE_ROOT / "contracts/examples/unity-mapping-proposal.json", proposal.model_dump(mode="json"))


if __name__ == "__main__":
    export_openapi()
    export_catalog_schema()
    export_event_schemas()
    export_fixture()
