"""Public API for the SceneOps Render Ops module."""

from .lab_router import create_render_lab_router
from .lab_service import RenderLabService

from .cache import plan_aov_cache, validate_aov_artifacts, validate_aov_set
from .capture import (
    AovCaptureWorker,
    CaptureCancellation,
    CaptureCapabilities,
    CapturePreview,
    CaptureResult,
    RenderCaptureAdapter,
)
from .jobs import RenderJobRepository, RenderQueue, transition_job
from .schemas import (
    AovArtifact,
    AovDependencySnapshot,
    AovPass,
    ApprovalState,
    ArtifactApprovalState,
    ArtifactRef,
    CachePlan,
    DifferenceMetrics,
    ExecutionMode,
    JobFailure,
    ManifestSummary,
    PortableRecipeCatalog,
    PortableRecipeDefinition,
    ProtectedRegion,
    ProtectedRegionResult,
    RecipeKind,
    RenderBrief,
    RenderCaptureCommand,
    RenderComparison,
    RenderJob,
    RenderJobPlanRequest,
    RenderJobState,
    RenderManifest,
    RenderRecipe,
    RenderVariant,
    RenderVariantApprovalSnapshot,
    SceneCameraRef,
    ValidationResult,
    WorkflowProvenance,
    WritebackOperation,
    WritebackApprovalSnapshot,
    WritebackProperty,
    WritebackProposal,
    WritebackTarget,
    summarize_manifest,
)
from .service import RenderOpsService
from .router import router
from .recipes import instantiate_recipe, load_recipe_catalog
from .validation import (
    compare_pixel_bytes,
    compare_protected_region,
    make_comparison,
    validate_writeback_result,
)
from .writeback import (
    ChangeSetApprovalVerifier,
    ChangePreview,
    SceneWritebackAdapter,
    WritebackCapabilities,
    WritebackExecution,
    WritebackExecutor,
    WritebackPolicy,
    WritebackResult,
    approve_writeback,
)

__all__ = [
    "create_render_lab_router",
    "AovArtifact",
    "AovCaptureWorker",
    "AovDependencySnapshot",
    "AovPass",
    "ApprovalState",
    "ArtifactApprovalState",
    "ArtifactRef",
    "CachePlan",
    "CaptureCancellation",
    "CaptureCapabilities",
    "CapturePreview",
    "CaptureResult",
    "ChangePreview",
    "ChangeSetApprovalVerifier",
    "DifferenceMetrics",
    "ExecutionMode",
    "JobFailure",
    "ManifestSummary",
    "PortableRecipeCatalog",
    "PortableRecipeDefinition",
    "ProtectedRegion",
    "ProtectedRegionResult",
    "RecipeKind",
    "RenderBrief",
    "RenderCaptureAdapter",
    "RenderCaptureCommand",
    "RenderComparison",
    "RenderJob",
    "RenderJobPlanRequest",
    "RenderJobRepository",
    "RenderJobState",
    "RenderManifest",
    "RenderOpsService",
    "RenderQueue",
    "RenderRecipe",
    "RenderVariant",
    "RenderVariantApprovalSnapshot",
    "SceneCameraRef",
    "SceneWritebackAdapter",
    "ValidationResult",
    "WorkflowProvenance",
    "WritebackCapabilities",
    "WritebackExecution",
    "WritebackExecutor",
    "WritebackOperation",
    "WritebackApprovalSnapshot",
    "WritebackPolicy",
    "WritebackProperty",
    "WritebackProposal",
    "WritebackResult",
    "WritebackTarget",
    "approve_writeback",
    "compare_pixel_bytes",
    "compare_protected_region",
    "instantiate_recipe",
    "load_recipe_catalog",
    "make_comparison",
    "plan_aov_cache",
    "summarize_manifest",
    "transition_job",
    "validate_aov_set",
    "validate_aov_artifacts",
    "validate_writeback_result",
    "router",
]
