import { createLight, type LookdevProject, type LookdevOperation, type MaterialState } from '../core/lookdev';
import { graphParameters } from '../core/shader-graph';
const pbr = [['metalness','金属度',0,1],['roughness','粗糙度',0,1],['normalScale','法线强度',0,4],['opacity','不透明度',0,1],['transmission','透射',0,1],['ior','折射率',1,2.333],['clearcoat','清漆',0,1],['clearcoatRoughness','清漆粗糙度',0,1],['alphaCutoff','透明裁切阈值',0,1],['emissiveIntensity','自发光强度',0,20]] as const;
export function LookdevInspector({ project, material, disabled, edit }: {project: LookdevProject; material: MaterialState; disabled: boolean; edit(ops: LookdevOperation[], summary: string): void}) {
  const patch = (key: string, value: string | number) => edit([{ kind: 'material.update', targetId: material.id, patch: { [key]: value } }], `调整${material.name}`);
  return <fieldset className="lookdev-inspector" disabled={disabled}><legend>材质与灯光</legend>
    <h3>{material.name}</h3>
    {(['baseColor','emissive'] as const).map((key,i) => <label key={key}>{['基础颜色','自发光颜色'][i]}<input aria-label={['基础颜色','自发光颜色'][i]} type="color" value={material[key]} onChange={e => patch(key,e.target.value)}/></label>)}
    {pbr.map(([key,label,min,max]) => <label key={key}>{label}<input aria-label={label} type="number" min={min} max={max} step="0.01" value={material[key]} onChange={e => { if(e.target.value !== '') patch(key,Number(e.target.value)); }}/></label>)}
    <label>透明模式<select value={material.alphaMode} onChange={e => patch('alphaMode',e.target.value)}><option value="OPAQUE">不透明</option><option value="MASK">裁切</option><option value="BLEND">混合</option></select></label>
    <details open><summary>程序化效果</summary>
      <label>图案<select value={material.procedural.type} onChange={e => edit([{kind:'material.effect.set',targetId:material.id,effect:{...material.procedural,type:e.target.value as MaterialState['procedural']['type']}}],'调整程序化图案')}><option value="none">无</option><option value="noise">噪声</option><option value="stripes">条纹</option><option value="checker">棋盘</option></select></label>
      {material.procedural.type !== 'none' && <><label>辅助颜色<input type="color" value={material.procedural.secondaryColor} onChange={e=>edit([{kind:'material.effect.set',targetId:material.id,effect:{...material.procedural,secondaryColor:e.target.value}}],'调整效果颜色')}/></label><label>影响通道<select value={material.procedural.target} onChange={e => edit([{kind:'material.effect.set',targetId:material.id,effect:{...material.procedural,target:e.target.value as 'color'|'roughness'}}],'调整效果通道')}><option value="color">颜色</option><option value="roughness">粗糙度</option></select></label>{(['scale','strength','contrast','direction','seed'] as const).map(key => <label key={key}>{({scale:'密度',strength:'强度',contrast:'对比',direction:'方向',seed:'随机种子'})[key]}<input type="number" value={material.procedural[key]} step={key==='seed'?1:.1} onChange={e => edit([{kind:'material.effect.set',targetId:material.id,effect:{...material.procedural,[key]:Number(e.target.value)}}],'调整程序化参数')}/></label>)}</>}
    </details>
    {material.shaderGraph && <details open><summary>Shader 参数</summary>{graphParameters(material.shaderGraph).map(p => <label key={p.key}>{p.label}<input type={p.kind==='parameter.color'?'color':'number'} value={p.value} step="0.01" min={p.kind==='parameter.float'?p.min:undefined} max={p.kind==='parameter.float'?p.max:undefined} onChange={e => edit([{kind:'material.graph.patch',targetId:material.id,parameters:{[p.key]:p.kind==='parameter.color'?e.target.value:Number(e.target.value)}}],'调整 Shader 参数')}/></label>)}</details>}
    <details><summary>资产灯光与预览环境</summary><p>修改的灯光随此资产应用。游戏全局灯光在场景工具中编辑；下方环境贴图只用于材质预览。</p><label>预览环境强度<input type="number" min="0" max="4" step=".1" value={project.environment.intensity} onChange={e => edit([{kind:'environment.update',patch:{intensity:Number(e.target.value)}}],'调整环境光')}/></label>
      <label>预览环境旋转<input type="number" min={-Math.PI} max={Math.PI} step=".1" value={project.environment.rotation} onChange={e=>edit([{kind:'environment.update',patch:{rotation:Number(e.target.value)}}],'环境旋转')}/></label>
      {project.lights.map(light => <div key={light.id}><h4>{light.name}</h4><label>启用<input type="checkbox" checked={light.enabled} onChange={e => edit([{kind:'light.update',targetId:light.id,patch:{enabled:e.target.checked}}],'切换灯光')}/></label><label>颜色<input type="color" value={light.color} onChange={e => edit([{kind:'light.update',targetId:light.id,patch:{color:e.target.value}}],'调整灯光颜色')}/></label><label>强度<input type="number" min="0" step=".1" value={light.intensity} onChange={e => edit([{kind:'light.update',targetId:light.id,patch:{intensity:Number(e.target.value)}}],'调整灯光强度')}/></label>{(['distance','angle','penumbra','width','height'] as const).filter(key=>key==='distance'?(light.type==='point'||light.type==='spot'):key==='angle'||key==='penumbra'?light.type==='spot':light.type==='rectArea').map(key=><label key={key}>{({distance:'影响距离',angle:'光锥角度',penumbra:'边缘柔和',width:'宽度',height:'高度'})[key]}<input type="number" min={key==='angle'||key==='width'||key==='height' ? .01 : 0} max={key==='angle'?Math.PI/2:key==='penumbra'?1:undefined} step=".1" value={light[key]} onChange={e=>edit([{kind:'light.update',targetId:light.id,patch:{[key]:Number(e.target.value)}}],'调整灯光形状')}/></label>)}{(['position','rotation'] as const).map(field => <div key={field}><span>{field==='position'?'位置（米）':'旋转（弧度）'}</span>{light[field].map((value,index) => <label key={index}>{['X','Y','Z'][index]}<input type="number" step=".1" value={value} onChange={e => {const vector = [...light[field]] as [number,number,number]; vector[index]=Number(e.target.value);edit([{kind:'light.update',targetId:light.id,patch:{[field]:vector}}],'移动灯光');}}/></label>)}</div>)}</div>)}
      {(['point','spot','directional','rectArea'] as const).map(type=><button key={type} onClick={() => edit([{kind:'light.add',light:createLight(type,crypto.randomUUID(),type)}],'添加灯光')}>{({point:'点光源',spot:'聚光灯',directional:'平行光',rectArea:'面积光'})[type]}</button>)}
    </details>
  </fieldset>;
}
